package com.cisco.la.model;

import java.util.ArrayList;
import java.util.List;

public class CourseHistoryModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public CourseHistoryModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIDIsNull() {
			addCriterion("HSTR_USR_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIDIsNotNull() {
			addCriterion("HSTR_USR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIDEqualTo(String value) {
			addCriterion("HSTR_USR_ID =", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotEqualTo(String value) {
			addCriterion("HSTR_USR_ID <>", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThan(String value) {
			addCriterion("HSTR_USR_ID >", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThanOrEqualTo(String value) {
			addCriterion("HSTR_USR_ID >=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThan(String value) {
			addCriterion("HSTR_USR_ID <", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThanOrEqualTo(String value) {
			addCriterion("HSTR_USR_ID <=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLike(String value) {
			addCriterion("HSTR_USR_ID like", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotLike(String value) {
			addCriterion("HSTR_USR_ID not like", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDIn(List<String> values) {
			addCriterion("HSTR_USR_ID in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotIn(List<String> values) {
			addCriterion("HSTR_USR_ID not in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDBetween(String value1, String value2) {
			addCriterion("HSTR_USR_ID between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotBetween(String value1, String value2) {
			addCriterion("HSTR_USR_ID not between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andCourseIDIsNull() {
			addCriterion("HSTR_CRS_ID is null");
			return (Criteria) this;
		}

		public Criteria andCourseIDIsNotNull() {
			addCriterion("HSTR_CRS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCourseIDEqualTo(String value) {
			addCriterion("HSTR_CRS_ID =", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDNotEqualTo(String value) {
			addCriterion("HSTR_CRS_ID <>", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDGreaterThan(String value) {
			addCriterion("HSTR_CRS_ID >", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDGreaterThanOrEqualTo(String value) {
			addCriterion("HSTR_CRS_ID >=", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDLessThan(String value) {
			addCriterion("HSTR_CRS_ID <", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDLessThanOrEqualTo(String value) {
			addCriterion("HSTR_CRS_ID <=", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDLike(String value) {
			addCriterion("HSTR_CRS_ID like", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDNotLike(String value) {
			addCriterion("HSTR_CRS_ID not like", value, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDIn(List<String> values) {
			addCriterion("HSTR_CRS_ID in", values, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDNotIn(List<String> values) {
			addCriterion("HSTR_CRS_ID not in", values, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDBetween(String value1, String value2) {
			addCriterion("HSTR_CRS_ID between", value1, value2, "courseID");
			return (Criteria) this;
		}

		public Criteria andCourseIDNotBetween(String value1, String value2) {
			addCriterion("HSTR_CRS_ID not between", value1, value2, "courseID");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table la_crs_history
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table la_crs_history
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 21 17:42:06 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}