package com.cisco.la.model;

public class CourseHistoryModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column la_crs_history.HSTR_USR_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	private String userID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column la_crs_history.HSTR_CRS_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	private String courseID;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column la_crs_history.HSTR_USR_ID
	 * @return  the value of la_crs_history.HSTR_USR_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public String getUserID() {
		return userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column la_crs_history.HSTR_USR_ID
	 * @param userID  the value for la_crs_history.HSTR_USR_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column la_crs_history.HSTR_CRS_ID
	 * @return  the value of la_crs_history.HSTR_CRS_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public String getCourseID() {
		return courseID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column la_crs_history.HSTR_CRS_ID
	 * @param courseID  the value for la_crs_history.HSTR_CRS_ID
	 * @mbg.generated  Thu Dec 21 17:51:54 CST 2017
	 */
	public void setCourseID(String courseID) {
		this.courseID = courseID;
	}
}